-- ==============================================================================
-- Supabase Quickstart: Create Todos Table & Seed Data
-- ==============================================================================

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  is_complete boolean default false,
  inserted_at timestamptz default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.todos enable row level security;

-- Allow anonymous / authenticated reads
create policy "Allow read access to all users" on public.todos
  for select using (true);

-- Allow anonymous / authenticated inserts for testing
create policy "Allow insert access to all users" on public.todos
  for insert with check (true);

-- Seed initial test items
insert into public.todos (name, is_complete) values
  ('Configure Supabase Client & Environment', true),
  ('Apply 001_initial_surge_schema.sql in Supabase SQL Editor', false),
  ('Verify SURGE Fleet & Telemetry Connectivity', false);
